#!/bin/bash
## Adjusting Readme.md

## Variables
SCRIPTBASEFILENAME=$(echo `basename $0 | cut -f 1 -d '.'`)
script_dir=$(dirname $0)
SCRIPTVARSDIR="$script_dir"/../../scriptvars/
STATICVARS="$SCRIPTVARSDIR"staticvariables.var
if
[[ -f $STATICVARS ]]
then
source $STATICVARS
else
echo "Static Vars File Missing, Exiting."
exit
fi
if
[[ -f $TEMPVARS ]]
then
source $TEMPVARS
else
echo "Temp Vars File Missing, Exiting."
exit
fi

RECENTRUN="$ENDTASKSCRIPTSLOGDIR""$SCRIPTBASEFILENAME".md

if
[[ -f $MAINREADME ]]
then
rm $MAINREADME
fi

if
[[ ! -f $MAINREADME ]]
then
cp $MAINREADMEDEFAULT $MAINREADME
fi

if
[[ -f $MAINREADME ]]
then
sed -i "s/NAMEOFTHEREPOSITORY/$REPONAME/" $MAINREADME
fi

if
[[ -n $STARTTIME ]]
then
STARTTIMEMD="Script Started $STARTTIME"
else
STARTTIMEMD="Error Setting Start Time."
fi
if
[[ -f $MAINREADME ]]
then
sed -i "s/LASTRUNSTART/$STARTTIMEMD/" $MAINREADME
fi

if
[[ -n $ENDTIME ]]
then
ENDTIMEMD="Script Ended $ENDTIME"
else
STARTTIMEMD="Error Setting End Time."
fi
if
[[ -f $MAINREADME ]]
then
sed -i "s/LASTRUNSTOP/$ENDTIMEMD/" $MAINREADME
fi

if
[[ -n $TOTALRUNTIME && -n $HOWMANYSOURCELISTS && -n $RECENTRUNLOGSDIRRAWMD ]]
then
RECENTRUNMAINLINKA="Script Took $TOTALRUNTIME Minutes To Filter $HOWMANYSOURCELISTS Lists. See Log Here."
else
RECENTRUNMAINLINKA="Error Calculating Script Run Time."
fi
if
[[ -f $MAINREADME ]]
then
sed -i "s/RECENTRUNMAINLINKA/$THEMAINLOGFILEA/" $MAINREADME
sed -i "s,RECENTRUNMAINLINKB,$RECENTRUNLOGSDIRRAWMD," $MAINREADME
fi

if
[[ -n $AVERAGEPARSETIME ]]
then
AVERAGELISTPARSINGTIMEMD="Average Parsing Time Was $AVERAGEPARSETIME Seconds."
else
AVERAGELISTPARSINGTIMEMD="Error Setting Average Parse Time."
fi
if
[[ -f $MAINREADME ]]
then
sed -i "s/AVERAGELISTPARSINGTIME/$AVERAGELISTPARSINGTIMEMD/" $MAINREADME
fi

if
[[ -n $HOWMANYTLDTOTAL ]]
then
THEAMOUNTOFVALIDTLDSMD="$HOWMANYTLDTOTAL Valid Top Level Domains."
else
THEAMOUNTOFVALIDTLDSMD="Error Setting The Amount Of Valid TLD's."
fi
if
[[ -f $MAINREADME ]]
then
sed -i "s/THEAMOUNTOFVALIDTLDS/$THEAMOUNTOFVALIDTLDSMD/" $MAINREADME
fi

if
[[ -n $HOWMANYTLDNEW ]]
then
THEAMOUNTOFNEWTLDSMD="$HOWMANYTLDNEW New TLD's."
else
THEAMOUNTOFNEWTLDSMD="."
fi
if
[[ -f $MAINREADME ]]
then
sed -i "s/THEAMOUNTOFNEWTLDS/$THEAMOUNTOFNEWTLDSMD/" $MAINREADME
fi

if
[[ -n $EDITEDALLPARSEDSIZEMB && -n $EDITEDALLPARSEDHOWMANYLINES ]]
then
EDITEDALLPARSEDMD="The Edited AllParsed File is $EDITEDALLPARSEDSIZEMB MB And Contains $EDITEDALLPARSEDHOWMANYLINES Domains."
else
EDITEDALLPARSEDMD="Error Calculating Size of AllParsed File."
fi
if
[[ -f $MAINREADME ]]
then
sed -i "s/EDITEDALLPARSEDINFO/$EDITEDALLPARSEDMD/" $MAINREADME
fi

if
[[ -n $RECENTRUNWITHOUTHTTPSMD && -n $HOWMANYLISTSWITHOUTHTTPS ]]
then
LISTSWITHOUTHTTPSLOGA="$HOWMANYLISTSWITHOUTHTTPS Lists That Do NOT Use https"
else
LISTSWITHOUTHTTPSLOGA="Error Setting https-less Link"
fi
if
[[ -f $MAINREADME ]]
then
sed -i "s/LISTSWITHOUTHTTPSLINKA/$LISTSWITHOUTHTTPSLOGA/" $MAINREADME
sed -i "s,LISTSWITHOUTHTTPSLINKB,$RECENTRUNWITHOUTHTTPSMD," $MAINREADME
fi

if
[[ -n $ALLPARSEDORIGRAW ]]
then
BIGAPLMD="$ALLPARSEDORIGRAW"
else
BIGAPLMD="Error Setting Original List Link."
fi
if
[[ -f $MAINREADME ]]
then
sed -i "s/BIGAPLRAWLINK/$BIGAPLMD/" $MAINREADME
fi

if
[[ -n $ALLPARSEDEDITRAW ]]
then
BIGAPLEMD="$ALLPARSEDEDITRAW"
else
BIGAPLEMD="Error Setting Edited List Link."
fi
if
[[ -f $MAINREADME ]]
then
sed -i "s/BIGAPLERAWLINK/$BIGAPLEMD/" $MAINREADME
fi

if
[[ -n $INSTALLERFILERAW ]]
then
INSTALLERMD="$INSTALLERFILERAW"
else
INSTALLERMD="Error Setting Installer Link."
fi
if
[[ -f $MAINREADME ]]
then
sed -i "s/INSTALLERLINKRAW/$INSTALLERMD/" $MAINREADME
fi
